package nl.kmartin.dartsmatcherapi.features.x01.x01dartbot.model;

/**
 * Represents a turn generated by an X01 Dart Bot.
 *
 * @param score             the points scored in the turn
 * @param doublesMissed     the number of doubles missed
 * @param checkoutDartsUsed the number of darts used for the checkout
 */
public record X01DartBotTurn(
        int score,
        Integer doublesMissed,
        Integer checkoutDartsUsed
) {
}
