# === Global environment properties ===

# Application Name
spring.application.name=darts-matcher-api

# Active profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Database
spring.data.mongodb.uri=${DB_URI:mongodb://localhost:27017/darts-matcher?replicaSet=rs0}